---
- hosts: all
  remote_user:  "{{ username }}"
  gather_facts: true
  become: yes
  tasks:
    - debug: msg="IP is {{ ansible_default_ipv4.address }}"
    - debug: msg="quorum is {{quorum}}"
    - debug: msg="{% if (groups.zookeeper|count) > 2} more than 2 {% endif %}"